criaCartao('Matemática', 'Qual é o resultado de 12 x 8?', '96')
criaCartao('Matemática', 'Quanto é 144 dividido por 12?', '12')
criaCartao('Matemática', 'O que é a área de um triângulo de base 10 e altura 5?', '25')
criaCartao('Matemática', 'Qual é o valor de x na equação 3x + 5 = 20?', '5')
criaCartao('Matemática', 'Se um carro viaja a 60 km/h, quantos km ele percorre em 2 horas?', '120 km')
criaCartao('Matemática', 'Qual é o valor de 20% de 500?', '100')
criaCartao('Matemática', 'Qual é a raiz quadrada de 64?', '8')
criaCartao('Matemática', 'Se uma pessoa paga R$ 320,00 por um produto de R$ 400,00, qual foi o percentual de desconto?', '20%')
criaCartao('Matemática', 'Se um policial percorre 300 metros em 15 segundos, qual é a sua velocidade média em m/s?', '20 m/s')
criaCartao('Matemática', 'Quantos segundos existem em 3 horas?', '10.800 segundos')
criaCartao('Matemática', 'Qual é o perímetro de um quadrado com lado de 6 metros?', '24 metros')
criaCartao('Matemática', 'Qual é a medida de um ângulo interno de um triângulo equilátero?', '60°')
criaCartao('Matemática', 'Qual é o valor de 2³?', '8')
criaCartao('Matemática', 'Quanto é 5³?', '125')
criaCartao('Matemática', 'Qual é o valor de 0,5 x 2?', '1')
criaCartao('Matemática', 'Qual é o valor de 15% de 600?', '90')
criaCartao('Matemática', 'Se um policial tem que dividir 1.800 horas de treinamento entre 6 meses, quantas horas ele treina por mês?', '300 horas')
criaCartao('Matemática', 'Qual é a soma dos ângulos internos de um quadrilátero?', '360°')
criaCartao('Matemática', 'Qual é a fórmula para calcular a área de um círculo?', 'A = πr²')
criaCartao('Matemática', 'Qual é o volume de um cubo de lado 4 cm?', '64 cm³')
criaCartao('Matemática', 'Quanto é 10²?', '100')
criaCartao('Matemática', 'Qual é o valor de x na equação x² = 49?', '7 ou -7')
criaCartao('Matemática', 'Qual é a fração equivalente a 0,75?', '3/4')
criaCartao('Matemática', 'Quanto é 7! (7 fatorial)?', '5040')
criaCartao('Matemática', 'Quanto é 10 + 15 × 3?', '55')
criaCartao('Matemática', 'Qual é o resultado de (3 + 5) × 2?', '16')
criaCartao('Matemática', 'Qual é o valor de 20 ÷ 4 + 3?', '8')
criaCartao('Matemática', 'Qual é a medida do ângulo reto?', '90°')
criaCartao('Matemática', 'Quanto é 7⁵?', '16807')
criaCartao('Matemática', 'Qual é a razão entre 15 e 5?', '3')
criaCartao('Matemática', 'Quanto é 120 dividido por 6?', '20')
criaCartao('Matemática', 'Qual é o valor de 25²?', '625')
criaCartao('Língua Portuguesa', 'O que é um sujeito na oração?', 'É o termo que indica quem ou o quê realiza a ação.')
criaCartao('Língua Portuguesa', 'Qual é a diferença entre sujeito simples e sujeito composto?', 'O sujeito simples tem apenas um núcleo, enquanto o composto tem dois ou mais núcleos.')
criaCartao('Língua Portuguesa', 'O que é um pronome pessoal?', 'Pronome que substitui ou acompanha o substantivo e indica a pessoa do discurso.')
criaCartao('Língua Portuguesa', 'Qual a função do verbo na frase?', 'O verbo indica a ação, o estado ou o fenômeno.')
criaCartao('Língua Portuguesa', 'O que é um predicado?', 'É a parte da oração que faz uma declaração sobre o sujeito.')
criaCartao('Língua Portuguesa', 'Qual é o tempo verbal da frase "Eu estudei muito"?', 'Pretérito perfeito')
criaCartao('Língua Portuguesa', 'Qual é o significado da palavra "compadecer"?', 'Sentir piedade ou compaixão.')
criaCartao('Língua Portuguesa', 'O que são palavras parônimas?', 'São palavras de sons semelhantes, mas de significados diferentes.')
criaCartao('Língua Portuguesa', 'O que é uma oração subordinada?', 'É uma oração que depende de outra para ter sentido completo.')
criaCartao('Língua Portuguesa', 'Qual a função do acento gráfico?', 'Indicar a tonicidade da sílaba ou distinguir palavras de significados diferentes.')
criaCartao('Língua Portuguesa', 'Quando usar "mas" e quando usar "mais"?', '"Mas" é uma conjunção adversativa, e "mais" é um advérbio de quantidade.')
criaCartao('Língua Portuguesa', 'Qual a diferença entre "por que", "porque", "porquê" e "por quê"?', '"Por que" é uma pergunta, "porque" é uma explicação, "porquê" é um substantivo e "por quê" é uma pergunta no final da frase.')
criaCartao('Língua Portuguesa', 'Qual é o significado de "hiperônimo"?', 'É uma palavra que tem um significado mais amplo e abrange outras palavras.')
criaCartao('Língua Portuguesa', 'O que é uma metáfora?', 'É uma figura de linguagem que consiste em comparar dois elementos sem usar palavras comparativas.')
criaCartao('Língua Portuguesa', 'O que é uma oração coordenada?', 'É uma oração independente que se liga a outra por uma conjunção.')
criaCartao('Língua Portuguesa', 'Quando usar a crase?', 'Usa-se a crase quando há a fusão da preposição "a" com o artigo feminino "a".')
criaCartao('Língua Portuguesa', 'Qual a diferença entre "a" e "há"?', '"A" é uma preposição e "há" é o verbo haver no sentido de existir.')
criaCartao('Língua Portuguesa', 'Qual a diferença entre "senão" e "se não"?', '"Senão" significa "caso contrário" ou "exceto", enquanto "se não" é uma condição.')
criaCartao('Língua Portuguesa', 'O que são adjetivos?', 'São palavras que qualificam ou caracterizam os substantivos.')
criaCartao('Língua Portuguesa', 'Qual é a diferença entre "dentre" e "dentro"?', '"Dentre" indica uma relação de interioridade dentro de um grupo, e "dentro" refere-se ao interior de algo.')
criaCartao('Língua Portuguesa', 'O que é um antônimo?', 'É uma palavra que tem o significado oposto de outra.')
criaCartao('Língua Portuguesa', 'O que é um adverbio?', 'É uma palavra que modifica o verbo, o adjetivo ou outro advérbio, indicando circunstâncias.')
criaCartao('Língua Portuguesa', 'O que são orações exclamativas?', 'São orações que expressam surpresa, emoção ou admiração.')
criaCartao('Língua Portuguesa', 'O que é uma oração afirmativa?', 'É uma oração que expressa uma certeza ou uma afirmação.')
criaCartao('Língua Portuguesa', 'Qual é o significado de "um anexo"?', 'É algo que está agregado ou acrescentado a outro documento ou objeto.')
criaCartao('Língua Portuguesa', 'Qual é a diferença entre "afim" e "a fim"?', '"Afim" significa semelhante ou relacionado, e "a fim" expressa vontade ou desejo.')


